
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 25 12:30:29 GMT-07:00 2017
//----------------------------------------------------

package Lex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLAN = 18;
  public static final int NUMERO = 2;
  public static final int STAND = 21;
  public static final int BACKWARD = 15;
  public static final int PUNTO_Y_COMA = 28;
  public static final int SLEEP = 7;
  public static final int FLY = 8;
  public static final int RESTA = 26;
  public static final int FORWARD = 14;
  public static final int LEVEL = 17;
  public static final int PARENTESIS_ABRIR = 29;
  public static final int OFF = 5;
  public static final int CAD = 24;
  public static final int SIGNO_DE_ASIGNACION = 25;
  public static final int ON = 4;
  public static final int UP = 10;
  public static final int LOOP = 6;
  public static final int ID = 3;
  public static final int LEFT = 12;
  public static final int EOF = 0;
  public static final int ROTATE = 16;
  public static final int PALABRA = 34;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int DOWN = 11;
  public static final int START = 23;
  public static final int SYNC = 35;
  public static final int ERROR = 33;
  public static final int LLAVE_CERRAR = 32;
  public static final int LLAVE_ABRIR = 31;
  public static final int END = 9;
  public static final int SPEED = 20;
  public static final int PARENTESIS_CERRAR = 30;
  public static final int RIGHT = 13;
  public static final int VAR = 22;
}

